# Generated by Django 4.2.2 on 2023-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
